spring:
  application:
    name: menu-service

  profiles:
    active: local
  config:
    import: configserver:http://localhost:8888  # Config Server URL
      
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/board-back?characterEncoding=UTF-8&serverTimezone=UTC
    username: ansdyd23
    password: Ka20140851!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 Actuator 엔드포인트 노출
        
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
          INFO: INFO

server:
  port: 9003
  servlet:
    session:
      timeout: 60m
      persistent: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
